airflow:
  image:
    repository: apache/airflow
    tag: 2.9.3

dags:
  gitSync:
    enabled: true
    repo: https://github.com/andrecaiado/airflow-deploy
    branch: main
    subPath: dags

config:
  core:
    load_examples: 'False'
  webserver:
    expose_config: 'True'
  logging:
    remote_logging: 'False'

workers:
  persistence:
    enabled: true
    size: 1Gi

webserver:
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    periodSeconds: 30
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    periodSeconds: 30